### ISSUE TITLE
Forbidden 403 error

### ISSUE THREAD

**Issue by manoharc07** [codeclassroom/CodeRunner#5]
I have attached the console log...

Submit any code 

**Desktop (please complete the following information):**
 - OS: [Win]
 - Python Version [3.6]
 - CodeRunner version [ 0.7]

CodeRunner was working till 27-05-2020
`Traceback (most recent call last):
  File "c:/Users/manoh/Desktop/Random Stuff/Scratch/scratch.py", line 19, in <module>
    r.run()
  File "C:\Users\manoh\AppData\Local\Programs\Python\Python37\lib\site-packages\coderunner\coderunner.py", line 227, in run
    token = self.__submit()
  File "C:\Users\manoh\AppData\Local\Programs\Python\Python37\lib\site-packages\coderunner\coderunner.py", line 165, in __submit
    with urllib.request.urlopen(req) as response:
  File "C:\Users\manoh\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\manoh\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "C:\Users\manoh\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Users\manoh\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "C:\Users\manoh\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:\Users\manoh\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden`

**Comment by manoharc07** [comment]
So i was able to fix the issue by using requests module instead of urllib, using urllib generates 403 forbidden.
