### ISSUE TITLE
urllib.error.HTTPError: HTTP Error 401: Unauthorized

### ISSUE THREAD

**Issue by soundaraj** [codeclassroom/CodeRunner#7]
in windows 10 , i tried this coderunner but i gives 401 error

`
>>> result = coderunner.code("print('hello')","Python3",path=False)
>>> result.run()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\SOUNDA~1\Desktop\PYTHON~1\ENV~1\lib\site-packages\coderunner\coderunner.py", line 227, in run
    token = self.__submit()
  File "C:\Users\SOUNDA~1\Desktop\PYTHON~1\ENV~1\lib\site-packages\coderunner\coderunner.py", line 165, in __submit
    with urllib.request.urlopen(req) as response:
  File "c:\users\soundara rajan\appdata\local\programs\python\python37\Lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "c:\users\soundara rajan\appdata\local\programs\python\python37\Lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "c:\users\soundara rajan\appdata\local\programs\python\python37\Lib\urllib\request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "c:\users\soundara rajan\appdata\local\programs\python\python37\Lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "c:\users\soundara rajan\appdata\local\programs\python\python37\Lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "c:\users\soundara rajan\appdata\local\programs\python\python37\Lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Unauthorized
`

**Comment by Bhupesh-V** [comment]
Hi @soundaraj :wave: ,  thanks for reporting this.
The issue arises due to the fact the Judge0 is now [freemium](https://github.com/judge0/api/issues/171), the default API URL, [https://api.judge0.com] is no longer available. To use the API through CodeRunner signup for a free (or paid) plan on [RapidAPI](https://rapidapi.com/hermanzdosilovic/api/judge0/pricing) & get your token

The PR #6 is a fix for this. It will be merge and released in 2-3 days
